version: '2.1'

services:
  graphtutorial:
    image: graphtutorial
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js